Repository FC-FastCatch/FastCatch-BackEnd, pull requests merged in 2023-11, with the labels that each got.

#11 [Feature] 로컬 mysql에 json 저장 및 도메인 엔터티
  build.gradle
  src/main/java/kr/co/fastcampus/fastcatch/common/config/AppConfig.java
  src/main/java/kr/co/fastcampus/fastcatch/domain/accommodation/entity/Accommodation.java
  src/main/java/kr/co/fastcampus/fastcatch/domain/cart/controller/CartController.java
  src/main/java/kr/co/fastcampus/fastcatch/domain/cart/dto/CartResponse.java
  src/main/java/kr/co/fastcampus/fastcatch/domain/cart/entity/Cart.java
  src/main/java/kr/co/fastcampus/fastcatch/domain/cartitem/entity/CartItem.java
  src/main/java/kr/co/fastcampus/fastcatch/domain/init/dto/FirstJsonReadDto.java
  src/main/java/kr/co/fastcampus/fastcatch/domain/init/dto/InitAccommodationDto.java
  src/main/java/kr/co/fastcampus/fastcatch/domain/init/entity/InitAccommodation.java
  src/main/java/kr/co/fastcampus/fastcatch/domain/init/exception/InitAccommodationExceptionCode.java
  src/main/java/kr/co/fastcampus/fastcatch/domain/init/exception/InitAccommodationFailedSaveException.java
  src/main/java/kr/co/fastcampus/fastcatch/domain/init/exception/InitAccommodationNotFoundException.java
  src/main/java/kr/co/fastcampus/fastcatch/domain/init/repository/InitAccommodationRepository.java
  src/main/java/kr/co/fastcampus/fastcatch/domain/init/service/InitAccommodationService.java
  src/main/java/kr/co/fastcampus/fastcatch/domain/member/controller/MemberController.java
  src/main/java/kr/co/fastcampus/fastcatch/domain/member/dto/MemberResponse.java
  src/main/java/kr/co/fastcampus/fastcatch/domain/member/entity/Member.java
  src/main/java/kr/co/fastcampus/fastcatch/domain/orderitem/entity/OrderItem.java
  src/main/java/kr/co/fastcampus/fastcatch/domain/orders/controller/OrderController.java
  src/main/java/kr/co/fastcampus/fastcatch/domain/orders/dto/OrderResponse.java
  src/main/java/kr/co/fastcampus/fastcatch/domain/orders/entity/OrderStatus.java
  src/main/java/kr/co/fastcampus/fastcatch/domain/orders/entity/Orders.java
  src/main/java/kr/co/fastcampus/fastcatch/domain/room/entity/Room.java
  src/main/resources/Accommodation.json
  src/main/resources/application.yml
Labels: enhancement, question

#19 chore: release 브랜치 체크 스타일 변경
  .github/workflows/ci.yml
Labels: bug

#32 Feature/12 Accommodation( 숙박) 도메인 완성
  build.gradle
  src/main/java/kr/co/fastcampus/fastcatch/common/exception/AccommodationNotFoundException.java
  src/main/java/kr/co/fastcampus/fastcatch/common/exception/DuplicatedRequest.java
  src/main/java/kr/co/fastcampus/fastcatch/common/exception/InvalidDateRangeException.java
  src/main/java/kr/co/fastcampus/fastcatch/common/exception/PastDateException.java
  src/main/java/kr/co/fastcampus/fastcatch/common/exception/RoomNotFoundException.java
  src/main/java/kr/co/fastcampus/fastcatch/common/exception/handler/GlobalExceptionHandler.java
  src/main/java/kr/co/fastcampus/fastcatch/common/response/ErrorCode.java
  src/main/java/kr/co/fastcampus/fastcatch/domain/accommodation/controller/AccommodationController.java
  src/main/java/kr/co/fastcampus/fastcatch/domain/accommodation/dto/AccommodationSummaryResponse.java
  src/main/java/kr/co/fastcampus/fastcatch/domain/accommodation/dto/request/AccommodationOptionSaveRequest.java
  src/main/java/kr/co/fastcampus/fastcatch/domain/accommodation/dto/request/AccommodationSaveRequest.java
  src/main/java/kr/co/fastcampus/fastcatch/domain/accommodation/dto/request/RoomImageSaveRequest.java
  src/main/java/kr/co/fastcampus/fastcatch/domain/accommodation/dto/request/RoomOptionSaveRequest.java
  src/main/java/kr/co/fastcampus/fastcatch/domain/accommodation/dto/request/RoomSaveRequest.java
  src/main/java/kr/co/fastcampus/fastcatch/domain/accommodation/dto/response/AccommodationInfoResponse.java
  src/main/java/kr/co/fastcampus/fastcatch/domain/accommodation/dto/response/AccommodationOptionResponse.java
  src/main/java/kr/co/fastcampus/fastcatch/domain/accommodation/dto/response/AccommodationPageResponse.java
  src/main/java/kr/co/fastcampus/fastcatch/domain/accommodation/dto/response/AccommodationSearchPageResponse.java
  src/main/java/kr/co/fastcampus/fastcatch/domain/accommodation/dto/response/AccommodationSearchResponse.java
  src/main/java/kr/co/fastcampus/fastcatch/domain/accommodation/dto/response/AccommodationSummaryResponse.java
  src/main/java/kr/co/fastcampus/fastcatch/domain/accommodation/dto/response/RoomImageResponse.java
  src/main/java/kr/co/fastcampus/fastcatch/domain/accommodation/dto/response/RoomOptionResponse.java
  src/main/java/kr/co/fastcampus/fastcatch/domain/accommodation/dto/response/RoomResponse.java
  src/main/java/kr/co/fastcampus/fastcatch/domain/accommodation/entity/Accommodation.java
  src/main/java/kr/co/fastcampus/fastcatch/domain/accommodation/entity/AccommodationOption.java
  src/main/java/kr/co/fastcampus/fastcatch/domain/accommodation/entity/Category.java
  src/main/java/kr/co/fastcampus/fastcatch/domain/accommodation/entity/Region.java
  src/main/java/kr/co/fastcampus/fastcatch/domain/accommodation/entity/Room.java
  src/main/java/kr/co/fastcampus/fastcatch/domain/accommodation/entity/RoomImage.java
  src/main/java/kr/co/fastcampus/fastcatch/domain/accommodation/entity/RoomOption.java
  src/main/java/kr/co/fastcampus/fastcatch/domain/accommodation/repository/AccommodationOptionRepository.java
  src/main/java/kr/co/fastcampus/fastcatch/domain/accommodation/repository/AccommodationRepository.java
  src/main/java/kr/co/fastcampus/fastcatch/domain/accommodation/repository/RoomOptionRepository.java
  src/main/java/kr/co/fastcampus/fastcatch/domain/accommodation/repository/RoomRepository.java
  src/main/java/kr/co/fastcampus/fastcatch/domain/accommodation/service/AccommodationService.java
  src/main/java/kr/co/fastcampus/fastcatch/domain/cart/controller/CartController.java
  src/main/java/kr/co/fastcampus/fastcatch/domain/cart/entity/Cart.java
  src/main/java/kr/co/fastcampus/fastcatch/domain/cart/entity/CartItem.java
  src/main/java/kr/co/fastcampus/fastcatch/domain/member/controller/MemberController.java
  src/main/java/kr/co/fastcampus/fastcatch/domain/order/entity/Order.java
  src/main/java/kr/co/fastcampus/fastcatch/domain/order/entity/OrderItem.java
  src/main/java/kr/co/fastcampus/fastcatch/domain/order/entity/OrderRecord.java
  src/main/java/kr/co/fastcampus/fastcatch/domain/order/repository/OrderRecordRepository.java
  src/main/java/kr/co/fastcampus/fastcatch/domain/order/service/OrderService.java
  src/main/java/kr/co/fastcampus/fastcatch/domain/room/entity/Room.java
Labels: enhancement

#38 fix: 테스트 서버 MySQL 에서 Room 테이블 인식못하는 버그
  src/main/java/kr/co/fastcampus/fastcatch/domain/accommodation/entity/Accommodation.java
Labels: bug

#39 fix: 테스트 서버 MySQL 에서 boolean : is prefix 생기는 버그
  src/main/java/kr/co/fastcampus/fastcatch/domain/accommodation/dto/response/AccommodationOptionResponse.java
  src/main/java/kr/co/fastcampus/fastcatch/domain/accommodation/dto/response/RoomOptionResponse.java
  src/main/java/kr/co/fastcampus/fastcatch/domain/accommodation/entity/AccommodationOption.java
  src/main/java/kr/co/fastcampus/fastcatch/domain/accommodation/entity/RoomOption.java
Labels: bug

#42 chore: release 브랜치 자동배포 파이프라인 구축 오타 수정
  .github/workflows/cd-release.yml
Labels: bug

#43 release 브랜치 자동배포 파이프라인 구축 오타 수정
  .github/workflows/cd-release.yml
Labels: bug

#49 Feature/48 숙박데이터 , 옵션들 리스트로 한번에 받아서 저장할 수 있도록 api 작성
  src/main/java/kr/co/fastcampus/fastcatch/domain/accommodation/controller/AccommodationController.java
  src/main/java/kr/co/fastcampus/fastcatch/domain/accommodation/dto/response/RoomResponse.java
  src/main/java/kr/co/fastcampus/fastcatch/domain/accommodation/service/AccommodationService.java
Labels: enhancement

#50 Develop refactor: 숙박과 옵션들 리스트로 한번에 저장할 수 있는 API 작성
  src/main/java/kr/co/fastcampus/fastcatch/domain/accommodation/controller/AccommodationController.java
  src/main/java/kr/co/fastcampus/fastcatch/domain/accommodation/dto/response/RoomResponse.java
  src/main/java/kr/co/fastcampus/fastcatch/domain/accommodation/service/AccommodationService.java
Labels: enhancement

#36 [Feature] 장바구니와 날짜 유틸
  src/main/java/kr/co/fastcampus/fastcatch/common/exception/CartItemNotFoundException.java
  src/main/java/kr/co/fastcampus/fastcatch/common/exception/CartNotFoundException.java
  src/main/java/kr/co/fastcampus/fastcatch/common/exception/InvalidDateRangeException.java
  src/main/java/kr/co/fastcampus/fastcatch/common/exception/InvalidHeadRangeException.java
  src/main/java/kr/co/fastcampus/fastcatch/common/response/ErrorCode.java
  src/main/java/kr/co/fastcampus/fastcatch/common/utility/AvailableOrderUtil.java
  src/main/java/kr/co/fastcampus/fastcatch/domain/cart/controller/CartController.java
  src/main/java/kr/co/fastcampus/fastcatch/domain/cart/dto/CartResponse.java
  src/main/java/kr/co/fastcampus/fastcatch/domain/cart/dto/request/CartItemRequest.java
  src/main/java/kr/co/fastcampus/fastcatch/domain/cart/dto/response/CartItemResponse.java
  src/main/java/kr/co/fastcampus/fastcatch/domain/cart/dto/response/CartResponse.java
  src/main/java/kr/co/fastcampus/fastcatch/domain/cart/entity/Cart.java
  src/main/java/kr/co/fastcampus/fastcatch/domain/cart/entity/CartItem.java
  src/main/java/kr/co/fastcampus/fastcatch/domain/cart/repository/CartItemRepository.java
  src/main/java/kr/co/fastcampus/fastcatch/domain/cart/repository/CartRepository.java
  src/main/java/kr/co/fastcampus/fastcatch/domain/cart/service/CartService.java
  src/main/java/kr/co/fastcampus/fastcatch/domain/member/repository/MemberRepository.java
  src/main/java/kr/co/fastcampus/fastcatch/domain/member/service/MemberService.java
  src/test/java/kr/co/fastcampus/fastcatch/http_test/accommodation/insert/accommodation-insert.http
  src/test/java/kr/co/fastcampus/fastcatch/http_test/accommodation/insert/accommodation-insertRoom.http
  src/test/java/kr/co/fastcampus/fastcatch/http_test/cart/delete/cart-deleteAll.http
  src/test/java/kr/co/fastcampus/fastcatch/http_test/cart/delete/cart-deleteItem-byCartItemId.http
  src/test/java/kr/co/fastcampus/fastcatch/http_test/cart/insert/cart-insertItem.http
  src/test/java/kr/co/fastcampus/fastcatch/http_test/cart/select/cart-getAll-byMemberId.http
Labels: enhancement

#44 Feature/15 회원가입 API
  build.gradle
  src/main/java/kr/co/fastcampus/fastcatch/FastcatchApplication.java
  src/main/java/kr/co/fastcampus/fastcatch/common/exception/DuplicatedEmailException.java
  src/main/java/kr/co/fastcampus/fastcatch/common/exception/DuplicatedNicknameException.java
  src/main/java/kr/co/fastcampus/fastcatch/common/response/ErrorCode.java
  src/main/java/kr/co/fastcampus/fastcatch/domain/cart/repository/CartRepository.java
  src/main/java/kr/co/fastcampus/fastcatch/domain/member/controller/MemberController.java
  src/main/java/kr/co/fastcampus/fastcatch/domain/member/dto/MemberResponse.java
  src/main/java/kr/co/fastcampus/fastcatch/domain/member/dto/request/MemberSignupRequest.java
  src/main/java/kr/co/fastcampus/fastcatch/domain/member/dto/response/MemberSignupResponse.java
  src/main/java/kr/co/fastcampus/fastcatch/domain/member/entity/Member.java
  src/main/java/kr/co/fastcampus/fastcatch/domain/member/passwordencoder/PasswordEncoder.java
  src/main/java/kr/co/fastcampus/fastcatch/domain/member/repository/MemberRepository.java
  src/main/java/kr/co/fastcampus/fastcatch/domain/member/service/MemberService.java
Labels: enhancement

#52 fix: 프론트 연결시 CORS 에러 문제 해결
  src/main/java/kr/co/fastcampus/fastcatch/common/config/WebConfig.java
Labels: bug

#46 Feature/20 주문 도메인 API 구현
  hs_err_pid13836.log
  hs_err_pid16540.log
  replay_pid13836.log
  replay_pid16540.log
  src/main/java/kr/co/fastcampus/fastcatch/common/baseentity/BaseEntity.java
  src/main/java/kr/co/fastcampus/fastcatch/common/exception/AlreadyOrderCanceledException.java
  src/main/java/kr/co/fastcampus/fastcatch/common/exception/AlreadyReservedRoomException.java
  src/main/java/kr/co/fastcampus/fastcatch/common/exception/InvalidHeadCountException.java
  src/main/java/kr/co/fastcampus/fastcatch/common/exception/InvalidOrderStatusException.java
  src/main/java/kr/co/fastcampus/fastcatch/common/exception/MemberNotFoundException.java
  src/main/java/kr/co/fastcampus/fastcatch/common/exception/OrderNotFoundException.java
  src/main/java/kr/co/fastcampus/fastcatch/common/exception/OrderUnauthorizedException.java
  src/main/java/kr/co/fastcampus/fastcatch/common/response/ErrorCode.java
  src/main/java/kr/co/fastcampus/fastcatch/domain/accommodation/service/AccommodationService.java
  src/main/java/kr/co/fastcampus/fastcatch/domain/cart/repository/CartItemRepository.java
  src/main/java/kr/co/fastcampus/fastcatch/domain/cart/service/CartService.java
  src/main/java/kr/co/fastcampus/fastcatch/domain/member/service/MemberService.java
  src/main/java/kr/co/fastcampus/fastcatch/domain/order/controller/OrderController.java
  src/main/java/kr/co/fastcampus/fastcatch/domain/order/dto/OrderResponse.java
  src/main/java/kr/co/fastcampus/fastcatch/domain/order/dto/request/OrderByCartRequest.java
  src/main/java/kr/co/fastcampus/fastcatch/domain/order/dto/request/OrderItemRequest.java
  src/main/java/kr/co/fastcampus/fastcatch/domain/order/dto/request/OrderRequest.java
  src/main/java/kr/co/fastcampus/fastcatch/domain/order/dto/response/OrderItemResponse.java
  src/main/java/kr/co/fastcampus/fastcatch/domain/order/dto/response/OrderPageResponse.java
  src/main/java/kr/co/fastcampus/fastcatch/domain/order/dto/response/OrderResponse.java
  src/main/java/kr/co/fastcampus/fastcatch/domain/order/dto/response/OrdersResponse.java
  src/main/java/kr/co/fastcampus/fastcatch/domain/order/entity/Order.java
  src/main/java/kr/co/fastcampus/fastcatch/domain/order/entity/OrderItem.java
  src/main/java/kr/co/fastcampus/fastcatch/domain/order/entity/OrderRecord.java
  src/main/java/kr/co/fastcampus/fastcatch/domain/order/entity/OrderStatus.java
  src/main/java/kr/co/fastcampus/fastcatch/domain/order/repository/OrderItemRepository.java
  src/main/java/kr/co/fastcampus/fastcatch/domain/order/repository/OrderRecordRepository.java
  src/main/java/kr/co/fastcampus/fastcatch/domain/order/repository/OrderRepository.java
  src/main/java/kr/co/fastcampus/fastcatch/domain/order/service/OrderService.java
Labels: enhancement

#53 Hotfix/51 프론트엔드 연결시 CORS 에러 나는 문제 해결
  src/main/java/kr/co/fastcampus/fastcatch/common/config/WebConfig.java
Labels: bug

#60 fix: 닉네임 조회 API 명세서에 맞게 수정
  src/main/java/kr/co/fastcampus/fastcatch/domain/member/controller/MemberController.java
  src/main/java/kr/co/fastcampus/fastcatch/domain/member/repository/MemberRepository.java
  src/main/java/kr/co/fastcampus/fastcatch/domain/member/service/MemberService.java
Labels: bug

#61 fix: 비밀번호 오류시 클라이언트에게 전송 못하게 막음
  src/main/resources/application.yml
Labels: bug

#64 fix: 숙박 전체 조회시 주소 추가
  src/main/java/kr/co/fastcampus/fastcatch/domain/accommodation/dto/response/AccommodationSummaryResponse.java
Labels: bug

#68 [Fix] 카트 동작은 하는데 restful 하지 않음
  src/main/java/kr/co/fastcampus/fastcatch/domain/cart/controller/CartController.java
  src/main/java/kr/co/fastcampus/fastcatch/domain/cart/dto/response/CartItemResponse.java
  src/main/java/kr/co/fastcampus/fastcatch/domain/cart/service/CartService.java
  src/main/java/kr/co/fastcampus/fastcatch/domain/order/service/OrderService.java
  src/test/java/kr/co/fastcampus/fastcatch/http_test/cart/delete/cart-deleteAll.http
  src/test/java/kr/co/fastcampus/fastcatch/http_test/cart/delete/cart-deleteItem-byCartItemId.http
  src/test/java/kr/co/fastcampus/fastcatch/http_test/cart/insert/cart-insertItem.http
  src/test/java/kr/co/fastcampus/fastcatch/http_test/cart/select/cart-getAll-byMemberId.http
Labels: bug fix, help wanted

#70 Feature/69 테스트 코드 틀 작성
  src/test/java/kr/co/fastcampus/fastcatch/common/ApiTest.java
  src/test/java/kr/co/fastcampus/fastcatch/common/DatabaseCleaner.java
  src/test/java/kr/co/fastcampus/fastcatch/common/DatabaseClearExtension.java
  src/test/java/kr/co/fastcampus/fastcatch/common/TestUtil.java
  src/test/java/kr/co/fastcampus/fastcatch/domain/accommodation/controller/AccommodationControllerTest.java
  src/test/java/kr/co/fastcampus/fastcatch/domain/accommodation/service/AccommodationServiceTest.java
Labels: enhancement

#73 Feature/72 주문 생성 (즉시&장바구니) API 응답 DTO 추가 구현
  src/main/java/kr/co/fastcampus/fastcatch/domain/order/controller/OrderController.java
  src/main/java/kr/co/fastcampus/fastcatch/domain/order/service/OrderService.java
Labels: enhancement

#75 [Feature]프론트 요구에 맞게 장바구니 기능 변경
  src/main/java/kr/co/fastcampus/fastcatch/domain/cart/controller/CartController.java
  src/main/java/kr/co/fastcampus/fastcatch/domain/cart/dto/response/CartItemListResponse.java
  src/main/java/kr/co/fastcampus/fastcatch/domain/cart/dto/response/CartItemResponse.java
  src/main/java/kr/co/fastcampus/fastcatch/domain/cart/dto/response/CartResponse.java
  src/main/java/kr/co/fastcampus/fastcatch/domain/cart/service/CartService.java
  src/test/java/kr/co/fastcampus/fastcatch/http_test/cart/insert/cart-insertItem.http
Labels: enhancement

#74 Feature/69 숙박 도메인 API 테스트 코드를 작성
  src/test/java/kr/co/fastcampus/fastcatch/domain/accommodation/controller/AccommodationControllerTest.java
  src/test/java/kr/co/fastcampus/fastcatch/domain/accommodation/service/AccommodationServiceTest.java
Labels: enhancement

#81 Feature/80 프론트엔드 배포 사이트 CORS 설정 및 테스트 도메인 삭제
  src/main/java/kr/co/fastcampus/fastcatch/common/config/WebConfig.java
  src/main/java/kr/co/fastcampus/fastcatch/domain/accommodation/dto/response/AccommodationSearchResponse.java
  src/main/java/kr/co/fastcampus/fastcatch/domain/test/InfoResponse.java
  src/main/java/kr/co/fastcampus/fastcatch/domain/test/SaveRequest.java
  src/main/java/kr/co/fastcampus/fastcatch/domain/test/TestController.java
  src/main/java/kr/co/fastcampus/fastcatch/domain/test/TestEntity.java
  src/main/java/kr/co/fastcampus/fastcatch/domain/test/TestRepository.java
  src/main/java/kr/co/fastcampus/fastcatch/domain/test/TestService.java
Labels: enhancement

#85 Feature/84 닉네임 조회 API 접근권한 변경
  src/main/java/kr/co/fastcampus/fastcatch/common/config/SecurityConfig.java
Labels: bug fix, enhancement

#101 test: 멤버 도메인 테스트 코드 작성
  src/test/java/kr/co/fastcampus/fastcatch/common/MemberTokenUtil.java
  src/test/java/kr/co/fastcampus/fastcatch/common/TestUtil.java
  src/test/java/kr/co/fastcampus/fastcatch/domain/member/controller/MemberControllerTest.java
  src/test/java/kr/co/fastcampus/fastcatch/domain/member/service/MemberServiceTest.java
Labels: enhancement

#100 Feature/47 주문 도메인 테스트 코드 작성
  src/main/java/kr/co/fastcampus/fastcatch/domain/order/service/OrderService.java
  src/test/java/kr/co/fastcampus/fastcatch/common/TestUtil.java
  src/test/java/kr/co/fastcampus/fastcatch/domain/order/controller/OrderControllerTest.java
  src/test/java/kr/co/fastcampus/fastcatch/domain/order/service/OrderServiceTest.java
Labels: enhancement

#105 Feature/104 오픈 api 브랜치 명 바꿔서 새로 업로드
  build.gradle
  src/main/java/kr/co/fastcampus/fastcatch/common/utility/api/OpenApiUtil.java
  src/main/java/kr/co/fastcampus/fastcatch/common/utility/api/dto/response/OpenApiResponseDto.java
  src/main/resources/application.yml
  src/test/java/kr/co/fastcampus/fastcatch/common/utility/api/OpenApiUtilTest.java
  src/test/java/kr/co/fastcampus/fastcatch/http_test/accommodation/insert/accommodation-insert.http
  src/test/java/kr/co/fastcampus/fastcatch/http_test/accommodation/insert/accommodation-insertRoom.http
  src/test/java/kr/co/fastcampus/fastcatch/http_test/cart/insert/cart-insertItem.http
Labels: enhancement

#106 docs: 리드미 작성 및 이미지 저장
  README.md
  img.png
  mini_project_8.png
  resultImage/내주문조회.png
  resultImage/로그인.png
  resultImage/로그인안했을시 주문목록조회 실패.png
  resultImage/숙박개별조회.png
  resultImage/숙박검색.png
  resultImage/숙박전체조회.png
  resultImage/시작일시가 과거일때.png
  resultImage/장바구니 삭제.png
  resultImage/장바구니 아이템 등록.png
  resultImage/장바구니 조회.png
  resultImage/종료일시가 시작일시보다 빠를때.png
  resultImage/주문 생성.png
  resultImage/주문 취소.png
  resultImage/주문목록조회성공.png
  resultImage/초기실행화면.png
  resultImage/회원가입.png
  resultImage/회원정보수정.png
  resultImage/회원조회.png
  프로젝트파이프라인.png
Labels: documentation

#107 Develop 리드미 작성 및 OpenAPI 로직 Merge, 테스트 코드 추가
  README.md
  build.gradle
  img.png
  mini_project_8.png
  resultImage/내주문조회.png
  resultImage/로그인.png
  resultImage/로그인안했을시 주문목록조회 실패.png
  resultImage/숙박개별조회.png
  resultImage/숙박검색.png
  resultImage/숙박전체조회.png
  resultImage/시작일시가 과거일때.png
  resultImage/장바구니 삭제.png
  resultImage/장바구니 아이템 등록.png
  resultImage/장바구니 조회.png
  resultImage/종료일시가 시작일시보다 빠를때.png
  resultImage/주문 생성.png
  resultImage/주문 취소.png
  resultImage/주문목록조회성공.png
  resultImage/초기실행화면.png
  resultImage/회원가입.png
  resultImage/회원정보수정.png
  resultImage/회원조회.png
  src/main/java/kr/co/fastcampus/fastcatch/common/utility/api/OpenApiUtil.java
  src/main/java/kr/co/fastcampus/fastcatch/common/utility/api/dto/response/OpenApiResponseDto.java
  src/main/java/kr/co/fastcampus/fastcatch/domain/cart/entity/Cart.java
  src/main/java/kr/co/fastcampus/fastcatch/domain/cart/repository/CartRepository.java
  src/main/java/kr/co/fastcampus/fastcatch/domain/order/service/OrderService.java
  src/main/resources/application.yml
  src/test/java/kr/co/fastcampus/fastcatch/common/MemberTokenUtil.java
  src/test/java/kr/co/fastcampus/fastcatch/common/TestUtil.java
  src/test/java/kr/co/fastcampus/fastcatch/common/utility/api/OpenApiUtilTest.java
  src/test/java/kr/co/fastcampus/fastcatch/domain/cart/controller/CartControllerTest.java
  src/test/java/kr/co/fastcampus/fastcatch/domain/cart/service/CartServiceTest.java
  src/test/java/kr/co/fastcampus/fastcatch/domain/member/controller/MemberControllerTest.java
  src/test/java/kr/co/fastcampus/fastcatch/domain/member/service/MemberServiceTest.java
  src/test/java/kr/co/fastcampus/fastcatch/domain/order/controller/OrderControllerTest.java
  src/test/java/kr/co/fastcampus/fastcatch/domain/order/service/OrderServiceTest.java
  src/test/java/kr/co/fastcampus/fastcatch/http_test/accommodation/insert/accommodation-insert.http
  src/test/java/kr/co/fastcampus/fastcatch/http_test/accommodation/insert/accommodation-insertRoom.http
  src/test/java/kr/co/fastcampus/fastcatch/http_test/cart/insert/cart-insertItem.http
  프로젝트파이프라인.png
Labels: documentation, enhancement
